### ISSUE TITLE
Development image

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/weblets_pocs#1]
based on ubuntu 20.04

```
      "apt update && apt upgrade -y && apt install mc curl git sudo -y",
      "yes | unminimize",
      "curl https://raw.githubusercontent.com/freeflowuniverse/crystaltools/development/install.sh > /tmp/install.sh", 
      "bash /tmp/install.sh",
      "source /root/env.sh",
      "export PUBSITE=https://github.com/threefoldfoundation/info_threefold_pub/tree/development/wiki_config",
      "cd /root && publishtools flatten",
      "curl -fsSL https://code-server.dev/install.sh | sh",
      # "sed -i 's/password.*/password: tfrocks/' ~/.config/code-server/config.yaml"
      # "apt-get autoremove && apt-get clean"
```

check https://docs.google.com/document/d/1SXfdUxUYmEKuJmf3SvomdI3I1skvN0-0LLA6ezYHoFo/edit#

- [x] dockerfile for the env should have redis, caddy, codeserver, golang build env, vlang build env, nodejs …
- [x] flist
- [x] terraform example to start it

**Comment by Omarabdul3ziz** [comment]
link for the flist 
https://hub.grid.tf/omarabdul3ziz.3bot/omarabdul3ziz-ubuntu-20.04-devenv.flist

**Comment by xmonader** [comment]
I tried sshing using planetary ip and public ip and I couldn't worked.

**Comment by xmonader** [comment]
flist: https://hub.grid.tf/omarabdul3ziz.3bot/omarabdul3ziz-ubuntu-20.04-devenv.flist
entrypoint: /start.sh
env: SSH_KEY

to be documented  https://github.com/threefoldtech/tf-images/blob/ubuntu_devenv/ubuntu_devenv/Dockerfile
