### ISSUE TITLE
poc1: pkid weblet

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/weblets_pocs#2]
weblet that has interacts with jimber api to store a key/value and retrieve by key

https://github.com/threefoldtech/pkid
https://github.com/threefoldtech/threefold_login_pkid_example
https://github.com/threefoldtech/pkid-node-client

example explaning how this work in python https://gist.github.com/xmonader/bac7ca75316fb0994dc0ed93e17f91b9

all data should be self-contained in this repo in `poc1` dir

- create a website vue based & ask for phone, email, doubleName, derivedSeed scopes
- after login there will be a variable in localStorage named `profile` that has derived seed
- from that seed you can get the keypair (public, private keys)
- using the pkid lib do getDoc, setDoc calls 

here's an example  https://github.com/threefoldtech/threefold_login_pkid_example/blob/99339383d168cd05a369d0c4654d80e53f6cca89/src/views/Home.vue#L686

![image](https://user-images.githubusercontent.com/64129/148406850-e79f2b6d-2ebb-4ba9-94d0-d4bd47f798a2.png)

**Comment by asamirr** [comment]
@xmonader is the derived seed the same as our mnemonics?

**Comment by xmonader** [comment]
It's the derived seed from threefold connect app. Has nothing todo with substrate mnemonics

**Comment by sameh-farouk** [comment]
**Status Update**
Implemented in https://github.com/threefoldtech/weblets_pocs/pull/7
