### ISSUE TITLE
poc3: Example on grid nodejs server as backend

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/weblets_pocs#9]
add an example on how to use twinserver as a backend to execute commands on the grid.
see: [twinserver](https://github.com/threefoldtech/grid3_client_ts/blob/development/docs/server.md)

**Comment by MohamedEssamAdawy** [comment]
Add a readme for poc3 https://github.com/threefoldtech/weblets_pocs/blob/development/poc3/README.md
